"""Matches

Revision ID: 00fbd0baed3a
Revises: 
Create Date: 2024-03-29 17:32:20.223844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fbd0baed3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('tournament_id', sa.Uuid(), nullable=False))
    op.add_column('match', sa.Column('round', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'match', 'tournament', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('public_profile_id_fkey', 'profile', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'round')
    op.drop_column('match', 'tournament_id')
    # ### end Alembic commands ###
