"""Features

Revision ID: 489ad22d7f5b
Revises: b69cbf69af8d
Create Date: 2024-03-30 04:43:40.210126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489ad22d7f5b'
down_revision: Union[str, None] = 'b69cbf69af8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'player_1_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'player_2_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile', 'scores',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('public_profile_id_fkey', 'profile', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('public_profile_id_fkey', 'profile', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('profile', 'scores',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('match', 'player_2_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'player_1_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
