"""Tournaments

Revision ID: a0f5001d8943
Revises: 
Create Date: 2024-03-29 14:52:34.606501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f5001d8943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('manager_id', sa.Uuid(), nullable=False))
    op.add_column('tournament', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('tournament', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tournament', sa.Column('starts_at', sa.DATE(), nullable=False))
    op.add_column('tournament', sa.Column('max_players', sa.INTEGER(), nullable=False))
    op.add_column('tournament', sa.Column('address', sa.TEXT(), nullable=False))
    op.add_column('tournament', sa.Column('winner_id', sa.Uuid(), nullable=True))
    op.add_column('tournament', sa.Column('status', postgresql.ENUM('WAITING', 'RUNNING', 'ENDED', name='tournament_status'), nullable=False))
    op.create_foreign_key(None, 'tournament', 'profile', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'tournament', 'profile', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournament_profile', 'status',
               existing_type=postgresql.ENUM('WAITING', 'ACCEPTED', 'DECLINED', 'BANNED', name='player_status'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'status')
    op.drop_column('tournament', 'winner_id')
    op.drop_column('tournament', 'address')
    op.drop_column('tournament', 'max_players')
    op.drop_column('tournament', 'starts_at')
    op.drop_column('tournament', 'created_at')
    op.drop_column('tournament', 'description')
    op.drop_column('tournament', 'manager_id')
    op.create_foreign_key('public_profile_id_fkey', 'profile', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###
