"""Matchesupdate

Revision ID: aafcf68752f6
Revises: 00fbd0baed3a
Create Date: 2024-03-29 17:43:57.836943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafcf68752f6'
down_revision: Union[str, None] = '00fbd0baed3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'player1_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('match', 'player2_id',
               existing_type=sa.UUID(),
               nullable=True)
    #op.drop_constraint('public_profile_id_fkey', 'profile', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('public_profile_id_fkey', 'profile', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('match', 'player2_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('match', 'player1_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
