"""Rounds

Revision ID: b69cbf69af8d
Revises: aafcf68752f6
Create Date: 2024-03-29 22:52:52.540460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69cbf69af8d'
down_revision: Union[str, None] = 'aafcf68752f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('player_1_scores', sa.INTEGER(), nullable=True))
    op.add_column('match', sa.Column('player_2_scores', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('public_profile_id_fkey', 'profile', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_column('match', 'player_2_scores')
    op.drop_column('match', 'player_1_scores')
    # ### end Alembic commands ###
